import type { INodeProperties } from 'n8n-workflow';

const resourceDisplayOptions = {
	resource: ['amazonData'],
};

const operationDisplayOptions = (operation: string) => ({
	resource: ['amazonData'],
	operation: [operation],
});

const sendToBody = (property: string) => ({
	send: {
		type: 'body' as const,
		property,
	},
});

const domainOptions = [
	{ name: 'United States (Amazon.com)', value: '1' },
	{ name: 'United Kingdom (Amazon.co.uk)', value: '2' },
	{ name: 'Germany (Amazon.de)', value: '3' },
	{ name: 'France (Amazon.fr)', value: '4' },
	{ name: 'Japan (Amazon.co.jp)', value: '5' },
	{ name: 'Canada (Amazon.ca)', value: '6' },
	{ name: 'Italy (Amazon.it)', value: '8' },
	{ name: 'Spain (Amazon.es)', value: '9' },
	{ name: 'India (Amazon.in)', value: '10' },
	{ name: 'Mexico (Amazon.com.mx)', value: '11' },
];

const productSearchFields: INodeProperties[] = [
	{
		displayName: 'Marketplace',
		name: 'domain',
		type: 'options',
		options: domainOptions,
		default: '1',
		required: true,
		displayOptions: { show: operationDisplayOptions('searchProducts') },
		description: 'Amazon marketplace to search',
		routing: sendToBody('domain'),
	},
	{
		displayName: 'Keyword',
		name: 'keyword',
		type: 'string',
		default: '',
		displayOptions: { show: operationDisplayOptions('searchProducts') },
		placeholder: 'wireless speaker',
		description: 'Title keywords. Spaces use AND matching; prefix a word with - to exclude it.',
		routing: sendToBody('keyword'),
	},
	{
		displayName: 'Page',
		name: 'page',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 1,
		displayOptions: { show: operationDisplayOptions('searchProducts') },
		description: 'Page number to return',
		routing: sendToBody('page'),
	},
	{
		displayName: 'Results Per Page',
		name: 'perPage',
		type: 'number',
		typeOptions: { minValue: 50, maxValue: 100 },
		default: 50,
		displayOptions: { show: operationDisplayOptions('searchProducts') },
		description: 'Number of products to return (50-100)',
		routing: sendToBody('perPage'),
	},
	{
		displayName: 'Filters',
		name: 'searchFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: operationDisplayOptions('searchProducts') },
		options: [
			{
				displayName: 'Brand Names',
				name: 'brand',
				type: 'string',
				typeOptions: { multipleValues: true },
				default: [],
				description: 'Brand names to match using OR logic',
				routing: sendToBody('brand'),
			},
			{
				displayName: 'Category Names',
				name: 'categoriesIncludeNames',
				type: 'string',
				typeOptions: { multipleValues: true },
				default: [],
				description: 'Subcategory names or full category paths to include',
				routing: sendToBody('categoriesIncludeNames'),
			},
			{
				displayName: 'Exclude Category Names',
				name: 'categoriesExcludeNames',
				type: 'string',
				typeOptions: { multipleValues: true },
				default: [],
				description: 'Subcategory names or full category paths to exclude',
				routing: sendToBody('categoriesExcludeNames'),
			},
			{
				displayName: 'Include Historical Data',
				name: 'history',
				type: 'boolean',
				default: false,
				description: 'Whether to include historical prices, rank, and sales data',
				routing: {
					send: {
						type: 'body',
						property: 'history',
						value: '={{$value ? 1 : 0}}',
					},
				},
			},
			{
				displayName: 'Maximum Monthly Sales',
				name: 'monthlySoldLte',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 1000,
				description: 'Maximum estimated units sold per month',
				routing: sendToBody('monthlySoldLte'),
			},
			{
				displayName: 'Maximum New Price',
				name: 'currentNewLte',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 10000,
				description: 'Maximum current new price in the marketplace minor currency unit (for example, cents)',
				routing: sendToBody('currentNewLte'),
			},
			{
				displayName: 'Maximum Rating',
				name: 'currentRatingLte',
				type: 'number',
				typeOptions: { minValue: 0, maxValue: 5, numberPrecision: 1 },
				default: 5,
				description: 'Maximum current rating',
				routing: sendToBody('currentRatingLte'),
			},
			{
				displayName: 'Maximum Review Count',
				name: 'currentCountReviewsLte',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 1000,
				description: 'Maximum current review count',
				routing: sendToBody('currentCountReviewsLte'),
			},
			{
				displayName: 'Minimum Monthly Sales',
				name: 'monthlySoldGte',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 100,
				description: 'Minimum estimated units sold per month',
				routing: sendToBody('monthlySoldGte'),
			},
			{
				displayName: 'Minimum New Price',
				name: 'currentNewGte',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 1000,
				description: 'Minimum current new price in the marketplace minor currency unit (for example, cents)',
				routing: sendToBody('currentNewGte'),
			},
			{
				displayName: 'Minimum Rating',
				name: 'currentRatingGte',
				type: 'number',
				typeOptions: { minValue: 0, maxValue: 5, numberPrecision: 1 },
				default: 4,
				description: 'Minimum current rating',
				routing: sendToBody('currentRatingGte'),
			},
			{
				displayName: 'Minimum Review Count',
				name: 'currentCountReviewsGte',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 0,
				description: 'Minimum current review count',
				routing: sendToBody('currentCountReviewsGte'),
			},
			{
				displayName: 'One Variation Per Product',
				name: 'singleVariation',
				type: 'boolean',
				default: true,
				description: 'Whether to return one representative variation for multi-variation products',
				routing: sendToBody('singleVariation'),
			},
			{
				displayName: 'Only FBA Buy Box',
				name: 'buyBoxIsFBA',
				type: 'boolean',
				default: true,
				description: 'Whether to return products whose Buy Box is fulfilled by Amazon',
				routing: sendToBody('buyBoxIsFBA'),
			},
			{
				displayName: 'Root Category Names',
				name: 'rootCategoryNames',
				type: 'string',
				typeOptions: { multipleValues: true },
				default: [],
				description: 'Amazon root category names to include',
				routing: sendToBody('rootCategoryNames'),
			},
			{
				displayName: 'Sort Rules (JSON)',
				name: 'sort',
				type: 'json',
				default: '[{"fieldName":"monthlySold","sortDirection":"desc"}]',
				description: 'Up to three sort objects with fieldName and sortDirection',
				routing: sendToBody('sort'),
			},
		],
	},
];

const productDetailFields: INodeProperties[] = [
	{
		displayName: 'ASINs',
		name: 'asins',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: operationDisplayOptions('getProductDetails') },
		placeholder: 'B08N5WRWNW,B072MQ5BRX',
		description: 'One to 40 uppercase ASINs, separated by commas',
		routing: sendToBody('asins'),
	},
	{
		displayName: 'Options',
		name: 'detailOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: operationDisplayOptions('getProductDetails') },
		options: [
			{
				displayName: 'Amazon Domain',
				name: 'amazonDomain',
				type: 'options',
				options: [
					{ name: 'Australia (Amazon.com.au)', value: 'amazon.com.au' },
					{ name: 'Brazil (Amazon.com.br)', value: 'amazon.com.br' },
					{ name: 'Canada (Amazon.ca)', value: 'amazon.ca' },
					{ name: 'France (Amazon.fr)', value: 'amazon.fr' },
					{ name: 'Germany (Amazon.de)', value: 'amazon.de' },
					{ name: 'India (Amazon.in)', value: 'amazon.in' },
					{ name: 'Italy (Amazon.it)', value: 'amazon.it' },
					{ name: 'Japan (Amazon.co.jp)', value: 'amazon.co.jp' },
					{ name: 'Mexico (Amazon.com.mx)', value: 'amazon.com.mx' },
					{ name: 'Spain (Amazon.es)', value: 'amazon.es' },
					{ name: 'United Kingdom (Amazon.co.uk)', value: 'amazon.co.uk' },
					{ name: 'United States (Amazon.com)', value: 'amazon.com' },
				],
				default: 'amazon.com',
				description: 'Amazon storefront to read',
				routing: sendToBody('amazonDomain'),
			},
			{
				displayName: 'Delivery ZIP Code',
				name: 'deliveryZip',
				type: 'string',
				default: '',
				description: 'Delivery postcode used for localized price and delivery information',
				routing: sendToBody('deliveryZip'),
			},
			{
				displayName: 'Device',
				name: 'device',
				type: 'options',
				options: [
					{ name: 'Desktop', value: 'desktop' },
					{ name: 'Mobile', value: 'mobile' },
					{ name: 'Tablet', value: 'tablet' },
				],
				default: 'desktop',
				description: 'Device profile used to retrieve the page',
				routing: sendToBody('device'),
			},
			{
				displayName: 'Language',
				name: 'language',
				type: 'string',
				default: 'en_US',
				placeholder: 'en_US',
				description: 'Amazon locale, such as en_US, de_DE, or ja_JP',
				routing: sendToBody('language'),
			},
			{
				displayName: 'Return Author Reviews',
				name: 'returnAuthorsReviews',
				type: 'boolean',
				default: false,
				description: 'Whether to include author review data',
				routing: sendToBody('returnAuthorsReviews'),
			},
			{
				displayName: 'Return Frequently Bought Together',
				name: 'returnBoughtTogether',
				type: 'boolean',
				default: false,
				description: 'Whether to include frequently bought together products',
				routing: sendToBody('returnBoughtTogether'),
			},
			{
				displayName: 'Return Related Products',
				name: 'returnRelatedProducts',
				type: 'boolean',
				default: false,
				description: 'Whether to include related products',
				routing: sendToBody('returnRelatedProducts'),
			},
		],
	},
];

const productHistoryFields: INodeProperties[] = [
	{
		displayName: 'ASINs',
		name: 'asin',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: operationDisplayOptions('getProductHistory') },
		placeholder: 'B08N5WRWNW,B072MQ5BRX',
		description: 'One to five ASINs, separated by commas',
		routing: sendToBody('asin'),
	},
	{
		displayName: 'Marketplace',
		name: 'domain',
		type: 'options',
		options: [
			{ name: 'Brazil (Amazon.com.br)', value: '12' },
			{ name: 'Canada (Amazon.ca)', value: '6' },
			{ name: 'France (Amazon.fr)', value: '4' },
			{ name: 'Germany (Amazon.de)', value: '3' },
			{ name: 'India (Amazon.in)', value: '10' },
			{ name: 'Italy (Amazon.it)', value: '8' },
			{ name: 'Japan (Amazon.co.jp)', value: '5' },
			{ name: 'Mexico (Amazon.com.mx)', value: '11' },
			{ name: 'Spain (Amazon.es)', value: '9' },
			{ name: 'United Kingdom (Amazon.co.uk)', value: '2' },
			{ name: 'United States (Amazon.com)', value: '1' },
		],
		default: '1',
		required: true,
		displayOptions: { show: operationDisplayOptions('getProductHistory') },
		description: 'Amazon marketplace to inspect',
		routing: sendToBody('domain'),
	},
	{
		displayName: 'Include Historical Data',
		name: 'history',
		type: 'boolean',
		default: true,
		displayOptions: { show: operationDisplayOptions('getProductHistory') },
		description: 'Whether to include price, sales-rank, and monthly-sales time series',
		routing: {
			send: {
				type: 'body',
				property: 'history',
				value: '={{$value ? 1 : 0}}',
			},
		},
	},
];

const reviewFields: INodeProperties[] = [
	{
		displayName: 'ASIN',
		name: 'asin',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: operationDisplayOptions('getReviews') },
		placeholder: 'B08N5WRWNW',
		description: 'Amazon product ASIN',
		routing: sendToBody('asin'),
	},
	{
		displayName: 'Marketplace',
		name: 'domainCode',
		type: 'options',
		options: [
			{ name: 'Australia', value: 'com.au' },
			{ name: 'Brazil', value: 'com.br' },
			{ name: 'Canada', value: 'ca' },
			{ name: 'France', value: 'fr' },
			{ name: 'Germany', value: 'de' },
			{ name: 'India', value: 'in' },
			{ name: 'Italy', value: 'it' },
			{ name: 'Japan', value: 'co.jp' },
			{ name: 'Mexico', value: 'com.mx' },
			{ name: 'Spain', value: 'es' },
			{ name: 'United Kingdom', value: 'co.uk' },
			{ name: 'United States', value: 'com' },
		],
		default: 'com',
		displayOptions: { show: operationDisplayOptions('getReviews') },
		description: 'Amazon marketplace whose reviews should be returned',
		routing: sendToBody('domainCode'),
	},
	{
		displayName: 'Filters',
		name: 'reviewFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: operationDisplayOptions('getReviews') },
		options: [
			{
				displayName: 'Filter by Keyword',
				name: 'filterByKeyword',
				type: 'string',
				default: '',
				description: 'Only return reviews containing this keyword',
				routing: sendToBody('filterByKeyword'),
			},
			{
				displayName: 'Format',
				name: 'formatType',
				type: 'options',
				options: [
					{ name: 'All Formats', value: 'all_formats' },
					{ name: 'Current Format', value: 'current_format' },
				],
				default: 'all_formats',
				description: 'Whether to include reviews for all product formats',
				routing: sendToBody('formatType'),
			},
			{
				displayName: 'Media',
				name: 'mediaType',
				type: 'options',
				options: [
					{ name: 'All Content', value: 'all_contents' },
					{ name: 'Media Reviews Only', value: 'media_reviews_only' },
				],
				default: 'all_contents',
				description: 'Whether to return all reviews or only reviews with media',
				routing: sendToBody('mediaType'),
			},
			{
				displayName: 'One-Star Reviews',
				name: 'star1Num',
				type: 'number',
				typeOptions: { minValue: 0, maxValue: 100 },
				default: 10,
				description: 'Maximum number of one-star reviews to return',
				routing: sendToBody('star1Num'),
			},
			{
				displayName: 'Reviewer Type',
				name: 'reviewerType',
				type: 'options',
				options: [
					{ name: 'All Reviews', value: 'all_reviews' },
					{ name: 'Verified Purchases Only', value: 'avp_only_reviews' },
				],
				default: 'all_reviews',
				description: 'Reviewer type to include',
				routing: sendToBody('reviewerType'),
			},
			{
				displayName: 'Sort By',
				name: 'sortBy',
				type: 'options',
				options: [
					{ name: 'Most Recent', value: 'recent' },
					{ name: 'Most Helpful', value: 'helpful' },
				],
				default: 'recent',
				description: 'Review ordering',
				routing: sendToBody('sortBy'),
			},
			...([2, 3, 4, 5].map((star) => ({
				displayName: `${star}-Star Reviews`,
				name: `star${star}Num`,
				type: 'number' as const,
				typeOptions: { minValue: 0, maxValue: 100 },
				default: 10,
				description: `Maximum number of ${star}-star reviews to return`,
				routing: sendToBody(`star${star}Num`),
			})) as INodeProperties[]),
		],
	},
];

const asinKeywordFields: INodeProperties[] = [
	{
		displayName: 'ASIN',
		name: 'asin',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: operationDisplayOptions('getAsinKeywords') },
		placeholder: 'B08N5WRWNW',
		description: 'Amazon product ASIN',
		routing: sendToBody('asin'),
	},
	{
		displayName: 'Marketplace',
		name: 'country',
		type: 'options',
		options: [
			{ name: 'Australia', value: 'AU' },
			{ name: 'Brazil', value: 'BR' },
			{ name: 'Canada', value: 'CA' },
			{ name: 'France', value: 'FR' },
			{ name: 'Germany', value: 'DE' },
			{ name: 'Italy', value: 'IT' },
			{ name: 'Japan', value: 'JP' },
			{ name: 'Mexico', value: 'MX' },
			{ name: 'Saudi Arabia', value: 'SA' },
			{ name: 'Spain', value: 'ES' },
			{ name: 'United Arab Emirates', value: 'AE' },
			{ name: 'United Kingdom', value: 'UK' },
			{ name: 'United States', value: 'US' },
		],
		default: 'US',
		displayOptions: { show: operationDisplayOptions('getAsinKeywords') },
		description: 'Amazon marketplace to query',
		routing: sendToBody('country'),
	},
	{
		displayName: 'Page',
		name: 'pageNum',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 1,
		displayOptions: { show: operationDisplayOptions('getAsinKeywords') },
		description: 'Page number to return',
		routing: sendToBody('pageNum'),
	},
	{
		displayName: 'Results Per Page',
		name: 'pageSize',
		type: 'number',
		typeOptions: { minValue: 10, maxValue: 100 },
		default: 100,
		displayOptions: { show: operationDisplayOptions('getAsinKeywords') },
		description: 'Number of keywords to return (10-100)',
		routing: sendToBody('pageSize'),
	},
	{
		displayName: 'Filters',
		name: 'keywordFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: operationDisplayOptions('getAsinKeywords') },
		options: [
			{
				displayName: 'Conditions',
				name: 'conditions',
				type: 'string',
				default: '',
				placeholder: 'nfPosition,isPurchaseKw',
				description: 'Comma-separated Nexscope keyword condition codes',
				routing: sendToBody('conditions'),
			},
			{
				displayName: 'Descending',
				name: 'desc',
				type: 'boolean',
				default: true,
				description: 'Whether to sort results in descending order',
				routing: sendToBody('desc'),
			},
			{
				displayName: 'Keyword',
				name: 'keyword',
				type: 'string',
				default: '',
				description: 'Only return traffic keywords matching this text',
				routing: sendToBody('keyword'),
			},
			{
				displayName: 'Sort By',
				name: 'sortBy',
				type: 'options',
				options: [
					{ name: 'Ad Rank', value: 'adLastRank' },
					{ name: 'Keyword Crawl Time', value: 'updateTime' },
					{ name: 'Monthly Search Volume', value: 'estSearchesNum' },
					{ name: 'Natural Rank', value: 'lastRank' },
					{ name: 'Search Rank', value: 'searchesRank' },
				],
				default: 'estSearchesNum',
				description: 'Metric used to sort the keyword list',
				routing: sendToBody('sortBy'),
			},
			{
				displayName: 'Time Slice Type',
				name: 'timePieceType',
				type: 'options',
				options: [
					{ name: 'Last N Days', value: 'latelyDay' },
					{ name: 'Month', value: 'month' },
					{ name: 'Week', value: 'week' },
				],
				default: 'latelyDay',
				description: 'Time granularity used for keyword metrics',
				routing: sendToBody('timePieceType'),
			},
			{
				displayName: 'Time Slice Value',
				name: 'timePieceValue',
				type: 'string',
				default: '7',
				description: 'Use 7 or 30 days, YYYY-MM for a month, or YYYY-MM-DD for a week',
				routing: sendToBody('timePieceValue'),
			},
		],
	},
];

const relatedAsinFields: INodeProperties[] = [
	{
		displayName: 'Reference ASIN',
		name: 'asin',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: operationDisplayOptions('findRelatedAsins') },
		placeholder: 'B08N5WRWNW',
		description: 'ASIN whose same-niche competitors should be found',
		routing: sendToBody('asin'),
	},
	{
		displayName: 'Marketplace',
		name: 'countryCode',
		type: 'options',
		options: [
			{ name: 'Germany', value: 'DE' },
			{ name: 'Japan', value: 'JP' },
			{ name: 'United States', value: 'US' },
		],
		default: 'US',
		displayOptions: { show: operationDisplayOptions('findRelatedAsins') },
		description: 'Supported marketplace for competitor discovery',
		routing: sendToBody('countryCode'),
	},
	{
		displayName: 'Page',
		name: 'page',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 1,
		displayOptions: { show: operationDisplayOptions('findRelatedAsins') },
		description: 'Page number to return',
		routing: sendToBody('page'),
	},
	{
		displayName: 'Results Per Page',
		name: 'pageSize',
		type: 'number',
		typeOptions: { minValue: 10, maxValue: 100 },
		default: 10,
		displayOptions: { show: operationDisplayOptions('findRelatedAsins') },
		description: 'Number of related ASINs to return (10-100)',
		routing: sendToBody('pageSize'),
	},
	{
		displayName: 'Filters',
		name: 'relatedFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: operationDisplayOptions('findRelatedAsins') },
		options: [
			{
				displayName: 'Maximum Annual Sales',
				name: 'salesVolumeT360Max',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 100000,
				description: 'Maximum sales volume over the last 360 days',
				routing: sendToBody('salesVolumeT360Max'),
			},
			{
				displayName: 'Maximum Price',
				name: 'priceMax',
				type: 'number',
				typeOptions: { minValue: 0, numberPrecision: 2 },
				default: 100,
				description: 'Maximum product price in the marketplace currency',
				routing: sendToBody('priceMax'),
			},
			{
				displayName: 'Maximum Rating',
				name: 'customerRatingMax',
				type: 'number',
				typeOptions: { minValue: 0, maxValue: 5, numberPrecision: 1 },
				default: 5,
				description: 'Maximum customer rating',
				routing: sendToBody('customerRatingMax'),
			},
			{
				displayName: 'Maximum Review Count',
				name: 'totalReviewsMax',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 10000,
				routing: sendToBody('totalReviewsMax'),
			},
			{
				displayName: 'Minimum Annual Sales',
				name: 'salesVolumeT360Min',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 1000,
				description: 'Minimum sales volume over the last 360 days',
				routing: sendToBody('salesVolumeT360Min'),
			},
			{
				displayName: 'Minimum Click Conversion Rate',
				name: 'clickConversionRateMin',
				type: 'number',
				typeOptions: { minValue: 0, maxValue: 1, numberPrecision: 4 },
				default: 0.05,
				description: 'Minimum seven-day click conversion rate, where 0.1 means 10%',
				routing: sendToBody('clickConversionRateMin'),
			},
			{
				displayName: 'Minimum Gross Profit Margin',
				name: 'grossProfitMarginMin',
				type: 'number',
				typeOptions: { minValue: 0, numberPrecision: 2 },
				default: 0,
				routing: sendToBody('grossProfitMarginMin'),
			},
			{
				displayName: 'Minimum Price',
				name: 'priceMin',
				type: 'number',
				typeOptions: { minValue: 0, numberPrecision: 2 },
				default: 10,
				description: 'Minimum product price in the marketplace currency',
				routing: sendToBody('priceMin'),
			},
			{
				displayName: 'Minimum Rating',
				name: 'customerRatingMin',
				type: 'number',
				typeOptions: { minValue: 0, maxValue: 5, numberPrecision: 1 },
				default: 4,
				description: 'Minimum customer rating',
				routing: sendToBody('customerRatingMin'),
			},
			{
				displayName: 'Minimum Review Count',
				name: 'totalReviewsMin',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 0,
				routing: sendToBody('totalReviewsMin'),
			},
			{
				displayName: 'Seller Countries',
				name: 'sellerCountry',
				type: 'string',
				default: '',
				placeholder: 'CN,US',
				description: 'Comma-separated seller country codes',
				routing: sendToBody('sellerCountry'),
			},
			{
				displayName: 'Sort By',
				name: 'sortField',
				type: 'string',
				default: 'salesVolumeT360',
				description: 'Nexscope related-ASIN response field used for sorting',
				routing: sendToBody('sortField'),
			},
			{
				displayName: 'Sort Direction',
				name: 'sortType',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
				default: 'desc',
				description: 'Direction used to sort competitors',
				routing: sendToBody('sortType'),
			},
		],
	},
];

export const amazonDataDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: resourceDisplayOptions },
		options: [
			{
				name: 'Find Related ASINs',
				value: 'findRelatedAsins',
				action: 'Find related products',
				description: 'Find same-niche Amazon competitors for an ASIN',
				routing: {
					request: {
						method: 'POST',
						url: '/api/skill-api/v1/skills/amazon-related-asins/run',
					},
				},
			},
			{
				name: 'Get ASIN Keywords',
				value: 'getAsinKeywords',
				action: 'Get ASIN keywords',
				description: 'Reverse-lookup the traffic keywords for an Amazon ASIN',
				routing: {
					request: {
						method: 'POST',
						url: '/api/skill-api/v1/skills/amazon-asin-keywords/run',
					},
				},
			},
			{
				name: 'Get Product Details',
				value: 'getProductDetails',
				action: 'Get product details',
				description: 'Retrieve Amazon listing content, pricing, ratings, variants, and media',
				routing: {
					request: {
						method: 'POST',
						url: '/api/skill-api/v1/skills/amazon-product-detail/run',
					},
				},
			},
			{
				name: 'Get Product History',
				value: 'getProductHistory',
				action: 'Get product history',
				description: 'Retrieve current product data and historical price, rank, and sales signals',
				routing: {
					request: {
						method: 'POST',
						url: '/api/skill-api/v1/skills/amazon-product-history/run',
					},
				},
			},
			{
				name: 'Get Reviews',
				value: 'getReviews',
				action: 'Get product reviews',
				description: 'Retrieve Amazon reviews with star, keyword, verification, and media filters',
				routing: {
					request: {
						method: 'POST',
						url: '/api/skill-api/v1/skills/amazon-reviews-list/run',
					},
				},
			},
			{
				name: 'Search Products',
				value: 'searchProducts',
				action: 'Search products',
				description: 'Search the Amazon product database using marketplace and commercial filters',
				routing: {
					request: {
						method: 'POST',
						url: '/api/skill-api/v1/skills/amazon-product-database-search/run',
					},
				},
			},
		],
		default: 'searchProducts',
	},
	...productSearchFields,
	...productDetailFields,
	...productHistoryFields,
	...reviewFields,
	...asinKeywordFields,
	...relatedAsinFields,
];
